language: ruby
rvm:
- 2.5.3
services:
- postgresql
env:
  matrix:
  - DB=postgresql
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
install:
- gem install bundler
- bundle install
- nvm install node
- node -v
- npm install -g yarn
- yarn
script:
- bundle exec rspec
deploy:
  provider: heroku
  app: calm-journey-55060
  run: rake db:migrate
  api_key:
    secure: jgsOlDG1qh4RT7PUR1H06vdJQGL4JQg99D/4rrN9Wx4Juh249joSigsJBXwkfVPd5Rs/9XHvCwzMEGuBd5b0PrlxnYSFISwOPc18/NKdCVodIMNrsy90yETB0JDbiDbEb3ey3kb2J+mrcVGaBnnmxkAGgAEmzzaQ3t28Cn1UdXJG1lVW2qQ+OnCd6C5+eMYd34jUInHJF2+Cz0o+S4sV4Haif33aUW1lm1KFD1JWL6jc985vWR9INMfHD5+toXxX81TeALlxigeAiHAq85670aFF5nEzNNFJbFHQ8yzht8M7OU8tbtJZiESqcJdUtIYyPQ8WYrcVe1YMb+4OL/7iVvnct62bRBlkHMqmv8nOUOlXXhN3P3/3myvA2f8MQu8cDp4lzj7YLsV30xCGUq6JI1nbEP41aloO3OMlQbOXGRV+zQnfj3v6RRrhm4uHYiHMCvskcW0AhzQ/Uel8VYD8m06VcNVO3lGLnsKnoTZ985iuwmpM68eLTsfFZnpCbGR8ETvneI1kLu5vGmxmjkP7S9gzX9ktjcW9Smuin+7/n3dYdAVxYWcOWHgMGVR0oKYFdj7IVZAz36mJJpc+Lm9AT80ntHL0YRJ6/yxgp9OUtnaQKKn3Pz31hMWnflFWdbICgrUaRde35wHpC4yikQR7Oacp9+YFABlk/M/tE07HNTw=
