language: ruby
rvm:
- 2.5.3
services:
- postgresql
env:
  matrix:
  - DB=postgresql
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:create db:migrate --trace
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
install:
- gem install bundler
- bundle install
- nvm install node
- node -v
- npm install -g yarn
- yarn
script:
- bundle exec rspec
deploy:
  provider: heroku
  app: calm-journey-55060
  run: rake db:migrate
  api_key:
    secure: HTyoaGEhlkMSkdpo4vk1f1Qg3bC4YHhhcABU0MB12D0FcjXTYPIlKAZMfmK1/33JWty7YW8yFcvgdGvIE47VFvrDxDKowD+ciLXZNRGGLwL2VVM9AU2qBtkKz5EXel/bvaQjg/PfIKYH3SnU76iOYPFb19Pmj1QDSEhVS1jnXTtChesk8pg3meiqYPFnoV11Im90YnVBt+tlUZstAzjK6c8N00S4Twd3Hq4wnfZo232zbVOyriHBsvpQenGtDRBh0BVWlHYcSAac6X+4yU8bBHnDJcRRB7iFc0DPuecaONfv345WUJro0AdN36omj2hFHdS/wWNCa0nxmFyrz5a2X4cMX0SYDsQl74CKAYIuymdjq0KdfV6Rlov5xAN5+YJSWEEC1OH3V9umexG1Dd6SLzqiN2mTdI7OT9gYfx6yhhtYgD0snx1kkMjE2Ac9P5EopkgNZN1uPgaoNC1u5fF2AnrAgeU/HRqM/969vOctZA5p42SpcwJDljvZbt4ZegyNRgGCQwtloqB5Iqs/vazxPVxnfG63sWHFo3KzE6hL15gC0Kedhe81B834m7fc04JIq3wiH288Q4O9ns3IbgL0UuMoQetGIeQ6BTOXGFGL3nP48VIWBQmodvQnOKtxZVBAXwHKcQ1vBbJEq/s26F1dkWikmIRlsgNQlWS6MWuzPpQ=
